@base_url = http://localhost:8080

POST {{base_url}}/api/login
Content-Type: application/json

{
    "email" : "super.admin@finapp.com",
    "password" : "Nop@ss1234"
}  

### Register User

POST {{base_url}}/api/register
Content-Type: application/json

{
    "first_name" : "Mostafa",
    "last_name" : "Jamal",
    "phone_number" : "+8801855555555",
    "email" : "sm.mostafajamal@gmail.com",
    "password" : "12345678",
    "confirm_password" : "12345678"
}   

