@base_url = http://localhost:8080
@jwt =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzdXBlci5hZG1pbkBmaW5hcHAuY29tIiwibmFtZSI6InN1cGVyIiwiaXNzIjoiRmluQXBwIiwiYXVkIjpbIkZpbkFwcCIsIkZpbkFwcCJdLCJleHAiOjE3ODQwMjk3MTEsIm5iZiI6MTc4NDAyNjExMSwiaWF0IjoxNzg0MDI2MTExfQ.2w-lF4xDWu3KZnzU9c6zWpYwKdAo3egczUBukAJ98m8

POST {{base_url}}/api/calculate-emi
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "lender": "Bank Asia",
    "installments": 60,
    "principle_amount": 2000000,
    "interest_rate": "14.05"
}