@base_url = http://localhost:8080/api
@jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzdXBlci5hZG1pbkBmaW5hcHAuY29tIiwibmFtZSI6InN1cGVyIiwiaXNzIjoiRmluQXBwIiwiYXVkIjpbIkZpbkFwcCIsIkZpbkFwcCJdLCJleHAiOjE3ODQyMTIwNTQsIm5iZiI6MTc4NDIwODQ1NCwiaWF0IjoxNzg0MjA4NDU0fQ.V10mF6rbT4JIHl27i_Ck39b3XhAaTbpXi_dyP3qFMug

POST {{base_url}}/calculate-emi
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "lender": "Bank Asia",
    "installments": 60,
    "principal_amount": 250000,
    "interest_rate": 14.05
}
###
POST {{base_url}}/emi-calculation-detail
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "lender": "Bank Asia",
    "installments": 60,
    "principal_amount": 250000,
    "interest_rate": 14.05
}